language: android
sudo: required
jdk: oraclejdk8

android:
 components:
 - tools
 - platform-tools
 - build-tools-25.0.1
 - android-25
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services

 licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'intel-android-extra-license.+'

before_script:
    - echo no | android create avd --force -n test -t "android-23" --abi $ANDROID_ABI --tag $ANDROID_TAG
    - emulator -avd test -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
